---
 colors:
   "BLACK": (0,0,0)
   "WHITE": (255,255,255)
   "RED": (255, 0, 0)
   "BLUE": (0,0,255)
   "YELLOW": (255,255,0)
   "GREEN": (0,215,0)
   "CYAN": (0,215,175)
   "PURPLE": (135,0,255)
   "PINK": (255,192,203)
   "LIGHTCYAN": (224,255,255)
   "AQUAMARINE": (127,255,212)
   "MEDIUMPURPLE": (135,95,215)
   "HOTPINK": (215,95,175)
   "DARKBLUE": (0,0,135)
   "AQUA": (0,255,255)
   "TURQOISE": (0,215,255)
   "DARKORANGE": (215,95,0)
   "TAN": (215,175,135)
   "GOLD": (215,175,0)
   "TURQOUISE": (64,224,208)
   "DEEPPINK": (255,0,135)
   "MAGENTA": (255,0,255)
   "BANANA" : (227, 207, 87)
   "OLIVE": (128,128,0)
   "DARKORCHID" : (154, 50, 205)
   "LIGHTYELLOW": (255,255,153)
   "PEACH": (255,218,185)
   "LIGHTGREY": (211,211,211)
   "SILVER": (192,192,192)
   "SIENNA": (160,82,45)
   "BOARDCOLOR": (0,0,0)
   "SURFACE": (255,255,255)
 RESOLUTION : (1032, 600)
 FONT: Arial
 FONTSIZE: 20
 WIDTHOFBOARD : 5
 MULTIPLIEDSIZE : 24
 NUMBERINROWTOWIN: 3
 NUMBEROFPAWNS: 3
 BOARDSIZE: 3